sudo: false
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - export PATH=~/bin:"$PATH"
language: go
go:
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9.x
script: make test-all
install: script/bootstrap
env:
  global:
    - AMAZON_S3_BUCKET=ci-cache
    - AMAZON_ACCESS_KEY_ID=AKIAJQCVTDEWQHRPBPGQ
    - secure: "XAZv5xyNjWt7F9hG0MZhDANVJ5h/ajEZvfJOEIZRQlE3X5x6oVgI8blLh/MmlRSF0kIyLckcn6t2ccjSOvwN2hca5bwZSjIqoKbJyNe2cmkxfi2432vEOu3Ve6PT5hZWX4R5RgT+xWyMjIJcdF3gUMP7ErXl64aEncBzeW6OoXM="
